services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: designflix-meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
